#pragma once

#ifndef SCREEN_HEIGHT
#define SCREEN_HEIGHT 1080
#endif

#ifndef SCREEN_WIDTH
#define SCREEN_WIDTH 1920
#endif

#define NEED_TO_ADD_SPIRAL 0.95F
#define SPIRAL_LIFE_SPAN 1000
#define DEFAULT_NUMBER_OF_SPIRALS 50

#define PARAMETER_A_FIRST 0.06F
#define PARAMETER_A_SECOND 0.12F

#define PARAMETER_B_FIRST 0.05F
#define PARAMETER_B_SECOND 0.05F
